apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: utxobr/monero:master
  path: monero
  docker:
    build:
      rawOptions:
      - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
      - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
      - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
      - --build-arg=NPROC=12
      - --build-arg=MONERO_REPOSITORY=https://github.com/monero-project/monero
      - --build-arg=MONERO_REVISION=c458d5fe401f460c5eed2146f74d77e1f840a19c
- image: utxobr/monero:p2pool-api-v0.17
  path: monero
  docker:
    build:
      rawOptions:
      - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
      - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
      - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
      - --build-arg=NPROC=12
      - --build-arg=MONERO_REPOSITORY=https://github.com/SChernykh/monero
      - --build-arg=MONERO_REVISION=7dbb0d1fc942292363483a8ef117859f66c21bee
- image: utxobr/p2pool:master
  path: p2pool
  docker:
    build:
      rawOptions:
      - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
      - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
      - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
      - --build-arg=NPROC=12
      - --build-arg=P2POOL_REPOSITORY=https://github.com/SChernykh/p2pool
      - --build-arg=P2POOL_REVISION=60a8538e0ca744e8fa9584bc1777031ca5b1f685
- image: utxobr/xmr-btc-swap:master
  path: xmr-btc-swap
  docker:
    build:
      rawOptions:
      - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
      - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
      - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
      - --build-arg=NPROC=12
      - --build-arg=XMRBTCSWAP_REPOSITORY=https://github.com/comit-network/xmr-btc-swap
      - --build-arg=XMRBTCSWAP_REVISION=b9d2e9c3aed01c724e392c7b202a9c07d6c7e400
- image: utxobr/electrs:master
  path: electrs
  docker:
    build:
      rawOptions:
      - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
      - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
      - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
      - --build-arg=NPROC=12
      - --build-arg=ELECTRS_REPOSITORY=https://github.com/romanz/electrs
      - --build-arg=ELECTRS_REVISION=b94c98fc310dd9ccda4e14c3be05e9cfc1815657
- image: utxobr/bitcoin:master
  path: bitcoin
  docker:
    build:
      rawOptions:
      - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
      - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
      - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
      - --build-arg=NPROC=12
      - --build-arg=BITCOIN_REPOSITORY=https://github.com/bitcoin/bitcoin
      - --build-arg=BITCOIN_REVISION=810ce36d54e4a047f27a099e8295ddadfced75a9
destinations:
- image: utxobr/monero:master
  newImage: utxobr/monero
  tags:
  - master
- image: utxobr/monero:p2pool-api-v0.17
  newImage: utxobr/monero
  tags:
  - p2pool-api-v0.17
- image: utxobr/p2pool:master
  newImage: utxobr/p2pool
  tags:
  - master
- image: utxobr/xmr-btc-swap:master
  newImage: utxobr/xmr-btc-swap
  tags:
  - master
- image: utxobr/electrs:master
  newImage: utxobr/electrs
  tags:
  - master
- image: utxobr/bitcoin:master
  newImage: utxobr/bitcoin
  tags:
  - master
---
images:
- image: utxobr/monero:master
  description: |-
    whatever latest commit is there on monero's
    `master` branch.
  args:
  - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
  - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
  - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
  - --build-arg=NPROC=12
  - --build-arg=MONERO_REPOSITORY=https://github.com/monero-project/monero
  - --build-arg=MONERO_REVISION=c458d5fe401f460c5eed2146f74d77e1f840a19c
  tags:
  - master
- image: utxobr/monero:p2pool-api-v0.17
  description: |-
    latest commits to the p2pool's temporary
    fork of monero based on the v0.17 release
    branch
  args:
  - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
  - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
  - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
  - --build-arg=NPROC=12
  - --build-arg=MONERO_REPOSITORY=https://github.com/SChernykh/monero
  - --build-arg=MONERO_REVISION=7dbb0d1fc942292363483a8ef117859f66c21bee
  tags:
  - p2pool-api-v0.17
- image: utxobr/p2pool:master
  description: |-
    p2p binary builds from latest commits of
    master branch of p2pool
  args:
  - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
  - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
  - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
  - --build-arg=NPROC=12
  - --build-arg=P2POOL_REPOSITORY=https://github.com/SChernykh/p2pool
  - --build-arg=P2POOL_REVISION=60a8538e0ca744e8fa9584bc1777031ca5b1f685
  tags:
  - master
- image: utxobr/xmr-btc-swap:master
  description: |-
    asb, swap, and kraken_ticker binary builds
    from comit-network's master branch
  args:
  - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
  - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
  - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
  - --build-arg=NPROC=12
  - --build-arg=XMRBTCSWAP_REPOSITORY=https://github.com/comit-network/xmr-btc-swap
  - --build-arg=XMRBTCSWAP_REVISION=b9d2e9c3aed01c724e392c7b202a9c07d6c7e400
  tags:
  - master
- image: utxobr/electrs:master
  description: electrs build from romanz' master branch
  args:
  - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
  - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
  - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
  - --build-arg=NPROC=12
  - --build-arg=ELECTRS_REPOSITORY=https://github.com/romanz/electrs
  - --build-arg=ELECTRS_REVISION=b94c98fc310dd9ccda4e14c3be05e9cfc1815657
  tags:
  - master
- image: utxobr/bitcoin:master
  description: |-
    bitcoind, bitcoin-cli, bitcoin-tx, and
    bitcoin-util from `master` branch.
  args:
  - --build-arg=RUST_IMAGE=index.docker.io/library/rust:1.55.0-bullseye@sha256:1b0490ed32286c0995520b64b6b6a98cc32b6e1be44228fdd3e75a7f1105ca28
  - --build-arg=DEBIAN_IMAGE=index.docker.io/library/debian:bullseye@sha256:826d8850098b954c3d67c2e45ea7a08fa681c128126ba01b35bd2689b1bb2e04
  - --build-arg=DISTROLESS_IMAGE=gcr.io/distroless/base-debian11:nonroot@sha256:21a86d92771aa0ee8fc238e94f1a3a5fbb2c0ad55adda8ad626a6dd1e7faaa8f
  - --build-arg=NPROC=12
  - --build-arg=BITCOIN_REPOSITORY=https://github.com/bitcoin/bitcoin
  - --build-arg=BITCOIN_REVISION=810ce36d54e4a047f27a099e8295ddadfced75a9
  tags:
  - master
