#@ load("@ytt:data", "data")

#@ def build_args(d):
#@   return ["--build-arg=" + x[0] + "=" + x[1] for x in dict(d).items()]
#@ end


---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  #@ for/end image in data.values.images:
  - image: #@ image.image + ":" + "_".join(image.tags)
    path: #@ image.type
    docker:
      build:
        rawOptions: #@ build_args(image.args)
destinations:
  #@ for/end image in data.values.images:
  - image: #@ image.image + ":" + "_".join(image.tags)
    newImage: #@ image.image
    tags: #@ image.tags

---
images:
  #@ for/end image in data.values.images:
  - image: #@ image.image + ":" + "_".join(image.tags)
    description: #@ image.description
    args: #@ build_args(image.args)
    tags: #@ image.tags
