images:
  - type: monero
    image: utxobr/monero
    tags: 
      - master
    args:
      MONERO_REPOSITORY: https://github.com/monero-project/monero
      MONERO_REVISION: gyr+gh://monero-project/monero#master
    description: |-
      whatever latest commit is there on monero's `master` branch.

  - type: monero
    image: utxobr/monero
    tags: 
      - p2pool-api-v0.17
    args:
      MONERO_REPOSITORY: https://github.com/SChernykh/monero
      MONERO_REVISION: gyr+gh://SChernykh/monero#p2pool-api-v0.17
    description: |-
      latest commits to the p2pool's temporary fork of monero based on the
      v0.17 release branch

  - type: p2pool
    image: utxobr/p2pool
    tags: 
      - master
    args:
      P2POOL_REPOSITORY: https://github.com/SChernykh/p2pool
      P2POOL_REVISION: gyr+gh://SChernykh/p2pool#master
    description: |-
      latest commits to master branch of p2pool
